version: '3.8'

services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    #  - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nest
  # app:
  #   build: ../
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DB_HOST: db
